### PR TITLE
Fix a few colors to make this look more like Atom

### PR DESCRIPTION
**Pull request by emroussel**
I use this theme and added a couple color customizations in my settings to make a couple small things look more like Atom, and thought I'd share them here.

I'm happy to discuss or make changes if you spot something I didn't, or feel like some changes aren't appropriate.

**Changes:**

```
"editor.findMatchHighlightBackground": "#314166",
"editor.foreground": "#ABB2C0",
"editorWidget.border": "#373D48",
"editorLineNumber.activeForeground": "#777D88",
"editorLineNumber.foreground": "#4B5365",
"editorRuler.foreground": "#abb2bf26",
"tab.activeForeground": "#D7DAE0"
```

With before/after and Atom screenshots:

`"editor.findMatchHighlightBackground": "#314166"`

VSCode (before)
screen shot 2018-05-12 at 18 38 02
Atom
screen shot 2018-05-12 at 18 31 52
VSCode (after)
screen shot 2018-05-12 at 18 31 47

--

`"editor.foreground": "#ABB2C0"`

VSCode (before)
screen shot 2018-05-12 at 18 41 14
Atom
screen shot 2018-05-12 at 18 40 06
VSCode (after)
screen shot 2018-05-12 at 18 41 28

--

`"editorWidget.border": "#373D48"`

VSCode (before)
screen shot 2018-05-12 at 18 43 57
Atom
No Atom equivalent, but this color fits better into Atom's color palette

VSCode (after)
screen shot 2018-05-12 at 18 43 42

--

`"editorLineNumber.activeForeground": "#777D88"`

VSCode (before)
screen shot 2018-05-12 at 18 49 56
Atom
screen shot 2018-05-12 at 18 50 11
VSCode (after)
screen shot 2018-05-12 at 18 51 35

--

`"editorLineNumber.foreground": "#4B5365"`

VSCode (before)
screen shot 2018-05-12 at 18 52 43
Atom
screen shot 2018-05-12 at 18 52 54
VSCode (after)
screen shot 2018-05-12 at 18 53 09

--

`"editorRuler.foreground": "#abb2bf26"`

VSCode (before)
screen shot 2018-05-12 at 18 57 06
Atom
screen shot 2018-05-12 at 18 57 24
VSCode (after)
screen shot 2018-05-12 at 18 56 52

--

`"tab.activeForeground": "#D7DAE0"`

VSCode (before)
screen shot 2018-05-12 at 18 59 03
Atom
screen shot 2018-05-12 at 18 59 22
VSCode (after)
screen shot 2018-05-12 at 18 59 16

### CODE REVIEW

**Comment by emroussel** [comment]
@akamud any updates on this?

**Comment by emroussel** [comment]
No worries, thanks!

**Comment by matthew-e-brown** [comment]
@akamud any plans/updates on merging this? Thanks!

**Comment by emroussel** [comment]
@matthew-e-brown I ended up creating a new theme with those changes (+ more) because I wasn't sure if this repo is still maintained. Still happy to see this PR getting merged, but feel free to use Atomize if you want to have these changes now and (in my opinion) a more atom like experience: https://github.com/emroussel/atomize

**Comment by matthew-e-brown** [comment]
@emroussel Fantastic! Thanks. Will check it out.

**Comment by akamud** [comment]
Hi everyone, indeed I haven't use VSCode for a while now (doing stuff on JetBrains Rider atm), that's why I didn't put much effort into maintaining this project anymore. I can't just accept the PR because I generate the theme automatically and directly from the Atom One Dark Syntax. So any PR I accept would be overridden, what I need to do is replicate the changes to my generator. I'm sorry about that.

Please remember that VSCode allows for **any** customization to be applied on top of any theme, like I mention in the [README](https://github.com/akamud/vscode-theme-onedark#customization), so that takes away the burden of releasing new versions so frequently.

About forks, I use a MIT license exactly to allow anyone to keep on going from where I stopped. Just remember that MIT requires you to reference the original copyright. I see a lot of forks from this theme that just ignores this completely and is, therefore, breaking the license.

**Comment by akamud** [comment]
Thank you again for your contributions, all your fixes are released in 2.2.0.

**Pull request closed without merging**
